#!/bin/bash
# 05_3_Backing_up_Inception_Key-SCRIPT.sh
#
# Tests all commands from §5.3, verifying:
# - Reconstruction of sharded XID
#
# Usage: bash 05_3_Backing_up_Inception_Key-SCRIPT.sh

set -e

echo "=== LEARNING XIDS §5.3: Backing Up Your Inception Key ==="

# Configuration

# Create output directory

OUTPUT_DIR="output/script-05-3-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$OUTPUT_DIR"

XID="ur:xid/tpsplftpspletpsotanshdhdcxnsvelewdmugsjksomhcsdngumosodnlffnlpcxfeylutcseeluatlyihdphyieadoyaylrtpsotansgylftanshflfaohdcxlumegtzorkdntkrolkosmyrffndiwkrofhbblfzerodipahhkkcejtatinbsjtintansgrhdcxlnjzbnfwasfshtfgvehhktdschdwttrtctdepkbyhlhkbdsogwashkgobsqzgwjtlfoycsfplftansfwlrhdghnejkhycajyhdseahmkpaylgdlfkklouotylujyhpjslobspmhhkolbcsuotstyaxkpmtoxssnyhdgachtypagdvedtytltvduetloyiojnpkssgusolpzeaepehhtpdmatlgtavostdifraeclfncnmomonldldssenblotngsbawentcydmecpdprdeotsabsgdnydrwsrlsatahkftaokebyjzmtieaolghddatansfphdcxayhkjpidzehpytiesnkofybgbbinntaezozstbctideyykdsbzylimwsvadplnlaoybwtpsotanshptansfwlrhdcxbtttfdutjsgopeptdsteioaasrrobtyladcwzmmsdicmfmmejymkprrnfraafxghgsrkyncyoypefgkihptihdgecxgdhemohhlgberkdsytsooepebtvwuewtbahflfaxtansgmgdjkdkueasinfmuohdlskejllfpddruoisoybstpsotansgmhdcxyaflntkectinioyttklocelbmhaseswnoeetdmtprnfmytmyhfghimjzhebnctftoycscstpsojziajljtjyjphsiajydpjeihkkoycsfncsfdoyaylttpsotansgylftanshflfaohdcxdncafzgdssbkftdpadrlgulgimbapdfgvtskwflsuyfnsgntcwdwidvyztdeaduttansgrhdcximsaoslsnlpsyafsdpfnsnfgoxnngdcfiezmlpeotifecnieprlgbbuocpvydlbklfoycsfplftansfwlrhdghescluyktcakgnynlzmotbnfrwywpihsgkiolkecxbzjkhlatsrpelknsgegsjkwpbboldasgsnbwssbtreutwessjnnsgdrhrlswtyhpyljpfwprvyrftngatsvwreclematgtfpfhbgrpmynefhdewkgrjyrptlwsvyrkongsaxhdsnsemoaatszteydydrlagdrpfdyadldsytisnywmspoeftnbwpcmlphddatansfphdcxgteojzfhbeynssmdvtzesernidsekpfwtbjlgmjneyhnolkbwnrhbbdssomkonguoybwtpsotanshptansfwlrhdcxkbpaaoahylolmtpduoltinldfsjydrtbstkiwedllumdtlkesaceytsrdandprlsgszspsmnweuecelnbyflvdidvsgdollgcxmdcewktkjplnftuefrtiloztfphflfaxtansgmgdfhylfspytkamieidnblyhkdahlfeossboybstpsotansgmhdcxhnpffrtokgrfleoeaxleimdigdoesgtkwmdpiapebgamckglndaefrrordwdswwdoycsfncsgeoycsfncsfloycsfncsfdoycsfncsgsoycscstpsojzjojljpjyhsidjzihdpjeihkkoyaylotpsotansgylftanshflfaohdcxwdolbgahbakkldwdfylkwfpagohkjetldmwyclmsvolsckftatjkjlptrdgmbybttansgrhdcxoxstsbuepsjlmtpkjpswcycsnydyemwfltdsrpsocwaminlohyfzbykeisuycfieoycsfncsgelfoycsfplftansfwlrhdghwplavlvadmnlfxbzhpambkpfzesbisreplnykpwpcsluaximmontcpfxrdrtftluvomdtlintiknsncahnfdndbsttmeaybsntsnrpkgaxztkkryjloxiypeglmwjtispfkedmvlkgfgwecslthkmkeeetuybbasjnfpiycegsnsttstpdwfdkwzfecpfepkbagdrfrfwttdknatwllridzsbswfnnctfzlfhddatansfphdcxhppmdplunnryeodsfnteaxesswehleghvlyadrbwfhihfgmubwfwfwolyajnbsieoybwtpsotanshptansfwlrhdcxgasawssomsgundwdlrmefnaewsmovlmwfteywpfymsswcxhlldgepteclyhhvtfmgskslspaspsppmhydwtdmwbyvlgdgtoewydwdrjolowlwdgytsamiagwpeaehflfaxtansgmgdwezmfyloimtaisgautmntioyaahfgssaoybstpsotansgmhdcxcavehnettizssaytfrbtdsroclurkpdnhdvseylfzskkbtwkessgvwtslgcwiazmoycsfncsfloycsfncsgroycsfncsfdoycsfncsgaoycscstpsojnjzhsjojyjljodpjeihkkdpkoeyoyaylrtpsotansgylftanshflfaohdcxonbbaxfdchqzlfcptlbbyachdypehyaxtecavlhymnmyceeekotpcamnamguclmotansgrhdcxcsrnchrnrpbsrnuecwaymoihplfnkgrdaxiefgpyidvysecnluhtwlwmpfwndnctoycscstpsoisfwgmhsiekojliaetoycsfncsfglfoycsfplftansfwlrhdghbzecvsspostkmylrprbazcistttkbdioatmeoxzoqzlejtbwvopknbkngustmotdykldgdbbgubgmntiateeaynbmulyykiasoinrdimmdwsqdsohdoletwngsrlnslbospdbaoyinenhknljetklpcxcmdtweoxcacekgutgseynlidfseejndeztlobsdlatgdpfftyaesdkcwmhrketsbcpldpejnehprhddatansfphdcxjemdmobewtihrohsgaghsglkgepdcmhdflhnamvegwssjzolpsjslesrwypkrydwoybwtpsotanshptansfwlrhdcxdteocmclktflvswzlpjzseqdhnjsinbgzetymefltsfmengyfpoxbsynoyfhtndigsgmfefrglmusoamwycetpctongdotimrohgrfoltsbyfmeeylmwbbhybdayhflfaxtansgmgdatbbwflplprkylglsbotloskuoidhplooybstpsotansgmhdcxrsfpfpfmldltkbsaamecmogabacsjtdedtsshlmdutaoaoylstndserdwdnedwmnoycsfzlftpsotngdgmgwhflfaxhdimemrfbyropanbtbvwstdwhywfldrfnlmtbylnihgwrlgwkbsnoleelumhmhtpvyluswptwyoyfygeahtkosgysfbwbdcmcsielunyytgmploxrdpymwhsoxfhkprnnspssepdhyssiytdhlatsgzsvwcxtdievtemgdjyweherntpltdsbbdypfbebafsnbiotkkbonwdktbbtlrtfskglfoycsfylftansfwlrhdropkhphfbesbwfmtaohgdslydlktattssgdmoxsgosasvyvlwdurjniylewewztkbyfhrnaabsemvwssimbzghfpcwtsprdkwybybtkgintkwkmontfwinhpfhlfcezsfzqzotpmotoldpftoyfeeobakpfddphtvdingtwswllecycxserkrytnltglrshffszoadoejnfdaahtnekpgwnbotdmjsfeztlgutayemguwsgyathdqdrywekgurwzhglolsoxpaempswzpywywnylpdenmshgeebajejymwjnfwhylgbzguhgndqzashklstittcluefhtpgmbswfgmmtpfpyhekpbgenkbjtmddygufldngsyttipfkkzeoxtdtidtmnbbkggdvskoisgdeornhnjzhgchtsjktoplgowmhddatansfphdcxiygoeedkoecsadztzcwtwtamreesfrvlenqzctwmdnfsptgswslghseyaafgpkaooybwtpsotanshptansfwlrhdcxglvalrhewsiegstkfxgatplgndlgolfgdmwllfzsyksnktwtinenenbwhfjsurktgsstcxcyhfzmeyaminrotyiyghgdvotdfylyasdpsswyndahlaclwlgmsnlahflfaxtansgmgdhgrsfemklbndmejtrdzthsgrutuykpnboybstpsotansgmhdcxiyvwcpcptddkeemdwfoylrrnspcttebgsbrnfmoetirfmwehhsrehdpmstdadaytoycfaorylftpsplrtpsokscfhsiaiajlkpjtjydpiajpihieihjtjyinhsjzdpioinjyiskpidoyadtpsojpiyjlhsiyftgwjtjzinjtihfpiaiajlkpjtjyoycfaorsldtpsotanshdhdcxnsvelewdmugsjksomhcsdngumosodnlffnlpcxfeylutcseeluatlyihdphyieadoytpsojsjkjkisguiniojtinjtiogrihkkjkgogmgstpsotpcxksenisjyjyjojkftdldlhsjoindmioinjyiskpiddmiajljndlkpjkihjpjkdlfwgmhsiekojliaetdljkjkishejkiniojtinjtiohejeihkkjkoytpsojoiyjlhsiyfthsiaiajlkpjtjyglhsjnihtpsoisfwgmhsiekojliaetoytpsojnjkjkisguiniojtinjtiogrihkktpsotansgylftanshftanehsksgdjkjkisdpihieeyececehescxfpfpfpfpfxeoglknhsfxehjzhtfygaehglghfeecfpfpfpfpgafdeceyjlgogmjehkkpjpjtihiygojtjlfgiddnfpgsjpjpfxeedlhdihdngdkpgwgmfxfgkninjlgmfyhfjkgmtansgrhdcxfhtkhnmyoeoyvdvdgolosrpfrosnrsaycmiycelnqdjyjzlplpeykgesmnvwoeimoytpsokscwiyjlhsiyfthsiaiajlkpjtjyguihjpkoiniaihfdjljnihjohsioihtpsotpcxksdkisjyjyjojkftdldlioinjyiskpiddmiajljndlfwgmhsiekojliaetdlfwgmhsiekojliaetoycscwtpsotpcxksdaisjyjyjojkftdldlhsjoindmioinjyiskpiddmiajljndlkpjkihjpjkdlfwgmhsiekojliaetoycseetpsotpcxjpisjyjyjojkftdldlioinjyiskpiddmiajljnoytpsojsjkjkisguiniojtinjtiogrihkkghihksjytpsoksgdjkjkisdpihieeyececehescxfpfpfpfpfxeoglknhsfxehjzhtfygaehglghfeecfpfpfpfpgafdeceyjlgogmjehkkpjpjtihiygojtjlfgiddnfpgsjpjpfxeedlhdihdngdkpgwgmfxfgkninjlgmfyhfjkgmoybetpsokoeydyeyendpdyeedpdyehgheheefteeetdpehdyftdydyoycfaorntpsotanshdhdcxnsvelewdmugsjksomhcsdngumosodnlffnlpcxfeylutcseeluatlyihdphyieadoyaxtpsotansghtaneidkkaddmdpdpdpdpdpfwfeflgaglcxgugufdcxgugaflglfpghgogmfedpdpdpdpdpbkgoehglgagodyjzfdfpfpfpfpfpgyfpfpfpfygtfpfpfpfpgsiaeogljlgshghfjegtimgoehgtghjefpfpfpfpioiyjthsisgmflgminenkpieecesguihiohfkoeefpkpkpjkgsimesbkieemeedneeecfegahdgwgrisfeglhgksfefpfpfpfpgahthgeceyhthgkskoiaflgofpfpfpfpfpfpfpfpfpfwjtgljlhkghgaehgliofpfpfpfggtfpfpfpfpgsiaeogljlgshghfjebkgtimgoehgtghjefpfpfpfwfphkihjeidkpjofxetihiyiejegejzgmeefdkkjpfyjkksgufljlghgtesdleejofdjegsjkghemdletgriygwhskoisecfgjtkkgmemfwkpgyeedlgwfwbkkkgufxghgrghkkhfenghiheefgeofdknhshfjtdldnjyehgwfyfefwiofsfsbkdpdpdpdpdpfeglfycxgugufdcxgugaflglfpghgogmfedpdpdpdpdpbkoycfaorylftpsplrtpsokscxjojpjlimihiajydpjkinjkjyihjpdpjkjohsiaihjkdpjkihiakpjpihhskpjyisoycfaorslrtpsotanshdhdcxnsvelewdmugsjksomhcsdngumosodnlffnlpcxfeylutcseeluatlyihdphyieadoytpsoiniajzhsfyinioihjkjytpsotansfphdcxhkrsoyhnoyuodrnsjewsylmybwmouonbtkglbbaxyakilfmnlaptpkjkiepszsdmoycscwtpsoksesisjyjyjojkftdldlioinjyiskpiddmiajljndlguinjkjyihjpgujohsiaihjkdlguihiakpjpihfpkpjyisdlfxgsfpjkdlgmfefpfygtfedmjnieoytpsojziyjlhsiyftgdjpjlimihiajytpsojzguinjkjyihjpgujohsiaihjkoyadtpsojziyjlhsiyftgdjpjlimihiajyoycfaorntpsotanshdhdcxnsvelewdmugsjksomhcsdngumosodnlffnlpcxfeylutcseeluatlyihdphyieadoyaxtpsotansghlfaohdfzmtiniolbreytcnyncnwmsoeyvtlkwzjzprlupebbbzghdnmnoyprenmdlflucaonsffelpfehkaaiyguzttartsfhdvtwfwdsboxfdlfbtwmwekbimdtemftatmhttbsoyaylrtpsotansgylftanshflfaohdcxplvdotinmnwensttrtlrtiisqzehrltlnlguhdludywzsebztnqdndwztpdazeqdtansgrhdcxfmlpjkhspautsfmwlndrpavobwpyotsazsdidwrnrpcylfintnwtgrnnhdhhpyjpoycscstpsojlhsjyjyihjkjyhsjyinjljtdpjeihkkoycsfncsfdlfoycsfplftansfwlrhdghdrdlgahpvleoesuywkzsiyfwsbwnhnbsmwpavaiovaftykcplgoyettklgrkuemdenwlimidktoewlnnylrltszccxdiktaywkfdzejsrdrorkzsdrmowtjoimyngeveonnlimgdfhdshtqzvestbzinhsrhmytpstcxjnbtgsgllewfdremfeihdskooecngogdrtbksgndwyhedtlugmahcktscmnegwylhddatansfphdcxiopakburhprngowmtshlrswzihbytpflgtrootzosfrpnnfprymuveasenotaeadoybwtpsotanshptansfwlrhdcxcfdaynjomwosutflfhchttsrcsadynmwpaftvwhfdkfrrtjncswtrhpynymdatrogsrfrytdflgaplnndkonpdcfvtgdiyzowsvlemheaynldpoxseqzcydmgtylhflfaxtansgmgdntpehhfxdlasbndrhlzteccletlbvevyoybstpsotansgmhdcxghchykwlghoxpftljectmyyldyamgycwamfwbnsbjelbsshkbzcnuttyrltlwtgmoycfaorylftpsplrtpsokseyjoihihjpdpihjtiejljpjkihjnihjtjydpiyjpjljndpieihkojpihkoinihktihjpdpeeehiaeshsenieehidehhseyihiyesenoycfaornlstpsotanshdhdcximprmsaylgfwcyjzzcamzmdrbdetjsrngamnbsfptbwtksihrhzonsahuthydwtboytpsojkjkiaisihjnhsftihjnjojzjlkkihihgmjljzihtpsokscsfdihhsiecxguihiakpjpinjykkcxgdjpjliojphsjnjnihjpoytpsojljkiaisihjnhsftktjljpjejkfgjljptpsojzguinjkjyihjpgujohsiaihjkoycfaorslntpsotanshdhdcxhecefsnnionspljpftktetwymnfmcyecveuotktpwenlhyhdpmpykpchcmzchywzoytpsojpihjtiejljpjkihjnihjtjyfxjljtjyihksjytpsoksglhfihjpiyinihiecxjojpihkoinjlkpjkcxihksjoihjpinihjtiaihdwcxktjljpjeihiecxjyjlioihjyisihjpcxjljtcxjkisjljpjycxjojpjlimihiajycxiyjljpcxguinjkjyihjpgujohsiaihjkoybetpsokoeydyeyendpdyeedpdyehghdyetfteyecdpehdyftdydyoytpsojsjpihjzhsjyinjljtjkisinjofwhsjkinjktpsoksiaguihiakpjpinjykkcxiajljzjzhsidjljphsjyinjljtcxjohsjpjyjtihjpcxktisjlcxkoihjpiniyinihiecxiajpihieihjtjyinhsjzjkcxjyisjpjlkpioiscxiajljnjninjydpjpihkoihhsjzcxhsjtiecxihjtiajpkkjojyihiecxjkishsjpinjtiooytpsojljoihihjpfejtiejljpjkihjnihjtjytpsoksguhgjpinjyihjkcxjkihiakpjpihdwcxktihjzjzdpjyihjkjyihiecxiajlieihcxktinjyiscxiajzihhsjpcxhsjyjyihjtjyinjljtcxjyjlcxjojpinkohsiakkdpjojpihjkihjpkoinjtiocxjohsjyjyihjpjtjkoytpsojoihjtiejljpjkihjnihjtjyguiajljoihtpsoksfeguihiakpjpinjykkcxhsjpiaisinjyihiajykpjpihdwcxiajpkkjojyjliojphsjoisiniacxinjnjojzihjnihjtjyhsjyinjljtdwcxjojpinkohsiakkcxjohsjyjyihjpjtjkoyadtpsojehsjyjyihjkjyhsjyinjljtoyaxtpsotansghlfaohdfzbzfslnetykknhplpwmhhcmcnwtfrwftogtrdadjtaxbsjkptmsmesbotldcstngyteisfhrntecemkoxtpueinjtmtfdrtvebwvtasbdcxeclafphthtfylfhgrhlabnoyaxtpsotansghlfaohdfzadpremeodpyteyknkoiavlwmntvddeeoosrphnylykfzstqdptguswfrtbpktpwnwlpteobzrnclvaadfmlthdoyguvarphgmuryjtkeeyimwdtyengrhdmepdbdbdbdtnenprrt"

XID_ID=$(envelope xid id $XID)
PASSWORD="test-password-for-tutorial"

echo ""
echo "Step 2: Create Backup Shares"
echo "================================="

SHARES=$(envelope sskr split --group "2-of-3" "$XID")
SHARE_ARRAY=( $SHARES )

echo "✅ Created 3 shares (any 2 can recover):"
echo "  Share 1: ${SHARE_ARRAY[0]:0:50}..."
echo "  Share 2: ${SHARE_ARRAY[1]:0:50}..."
echo "  Share 3: ${SHARE_ARRAY[2]:0:50}..."

echo "${SHARE_ARRAY[0]}" > $OUTPUT_DIR/01-xid-share1.ur
echo "${SHARE_ARRAY[1]}" > $OUTPUT_DIR/02-xid-share2.ur
echo "${SHARE_ARRAY[2]}" > $OUTPUT_DIR/03-xid-share3.ur

echo ""
echo "Step 3: Test Recovery Before Distribution"
echo "================================="

RECOVERED=$(envelope sskr join "${SHARE_ARRAY[0]}" "${SHARE_ARRAY[1]}")
ORIGINAL_DIGEST=$(envelope digest "$XID")
RECOVERED_DIGEST=$(envelope digest "$RECOVERED")

if [ "$ORIGINAL_DIGEST" = "$RECOVERED_DIGEST" ]; then
    echo "✅ Recovery test passed (shares 1+2)"
else
    echo "❌ Recovery failed - DO NOT proceed"
    exit 1
fi

RECOVERED_23=$(envelope sskr join "${SHARE_ARRAY[1]}" "${SHARE_ARRAY[2]}")
RECOVERED_13=$(envelope sskr join "${SHARE_ARRAY[0]}" "${SHARE_ARRAY[2]}")
DIGEST_23=$(envelope digest $RECOVERED_23)
DIGEST_13=$(envelope digest $RECOVERED_13)

if [ "$ORIGINAL_DIGEST" = "$RECOVERED_DIGEST" -a "$ORIGINAL_DIGEST" = "$DIGEST_23" -a "$ORIGINAL_DIGEST" = "$DIGEST_13" ]; then
    echo "✅ All share combinations verified"
else
    echo "❌ Additional recoveries failed - DO NOT proceed"
    exit 1
fi

echo ""
echo "==============================="
echo "All Tutorial §5.3 Tests Passed!"
echo "==============================="
echo ""
echo "Output files saved to: $OUTPUT_DIR/"
ls -la "$OUTPUT_DIR/"
